### ISSUE TITLE
Engine.zip contains Malware

### ISSUE THREAD

**Issue by vanlueckn** [DanielBoxer/UVgami#3]
I checked the binaries in the latest Release Engine.zip.

The binaries do contain malware.

You can check the virustotal scans of the binary here:

Windows: https://www.virustotal.com/gui/file/273acc0c5f29ce42ce7ae7fca2e8e9fe55551f0d6de24a8835bb758bfd01cc95

**Comment by danielboxer** [comment]
There is definitely no malware in the engine binaries.

Virus scans often have false positives because they’re just looking for patterns that the file shares with malicious code.

For example, this cmake project found [here ](https://gitlab.com/CLIUtils/modern-cmake/-/tree/master/examples/extended-project) is also flagged as a trojan (https://www.virustotal.com/gui/file/083ddf92373a3111a0bafe2f353e441589425df76ff3cf61c125c53e6adfbb05).
